// File generated by FlutterFire CLI
// ignore_for_file: kind=dotenv

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'your-web-api-key-here',
        appId: 'your-web-app-id-here',
        messagingSenderId: 'your-sender-id-here',
        projectId: 'your-project-id-here',
        authDomain: 'your-project-id.firebaseapp.com',
        storageBucket: 'your-project-id.appspot.com',
      );
    }

    return const FirebaseOptions(
      apiKey: 'your-api-key-here',
      appId: 'your-app-id-here',
      messagingSenderId: 'your-sender-id-here',
      projectId: 'your-project-id-here',
      authDomain: 'your-auth-domain-here',
      storageBucket: 'your-storage-bucket-here',
    );
  }
}
