// File generated by FlutterFire CLI
// ignore_for_file: kind=dotenv

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by importing the FirebaseOptions for '
        'web instead of default FirebaseOptions for another platform.',
      );
    }

    return const FirebaseOptions(
      apiKey: 'your-api-key-here',
      appId: 'your-app-id-here',
      messagingSenderId: 'your-sender-id-here',
      projectId: 'your-project-id-here',
      authDomain: 'your-auth-domain-here',
      storageBucket: 'your-storage-bucket-here',
    );
  }
}
